action_forever_until_error: revamp inotifywait
Now inotifywait is implemented in the script using
Linux::Inotify2, to have more control over the
events. Especially also directory events are now watched.
Also there's a verbose option, which is temporarily
switched on in the make wrapper action.